---
# tasks file for lighthouse-role
pre_tasks:
    - name: Install git
      become: true
      yum:
        name: git
        state: present

- name: Copy lighthouse from git
    git:
      repo: "{{ lighthouse_vcs }}"
      version: master
      dest: "{{ lighthouse_location_dir }}"
    become: true
- name: Create lighthouse config
    become: true
    template:
      src: lighthouse.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      mode: 0644
    notify: Reload nginx service
post_tasks:
  - name: Show connect URL lighthouse
    debug:
      msg: "http://{{ ansible_host }}/#http://{{ hostvars['clickhouse-01'].ansible_host }}:8123/?user={{ clickhouse_user }}"
